--- #YAML:1.0
name:                Tk-EntrySet
version:             0.09
abstract:            display/edit a list of values in a Set of Widgets.
license:             perl
author:              
    - Ch.Lamprecht <ch.l.ngre@online.de>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Tk:                            804.027
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
