--- #YAML:1.0
name:               Tk-EntrySet
version:            0.08
abstract:           display/edit a list of values in a Set of Widgets.
author:
    - Ch.Lamprecht <ch.l.ngre@online.de>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Tk:  804.027
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
